name: delivery_user_app
description: Wassle - Customer App
publish_to: 'none'
version: 1.0.7

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  provider: ^6.1.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  socket_io_client: ^2.0.3+1
  shared_preferences: ^2.2.2
  flutter_svg: ^1.1.6
  intl: ^0.20.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.2
  permission_handler: ^12.0.1
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/images/ar/
    - assets/images/en/

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/app_icon.png"
  android: false
  ios: true
  web: false

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon.png"
