name: delivery_driver_app
description: Delivery System - Driver App
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  provider: ^6.1.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  socket_io_client: ^2.0.3+1
  shared_preferences: ^2.2.2
  flutter_svg: ^1.1.6
  intl: ^0.20.2
  image_picker: ^1.0.7
  path: ^1.8.3
  url_launcher: ^6.2.2
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  zego_uikit_prebuilt_call: ^4.21.1
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
